version: "3.9"

services:
  db_server:
    image: mariadb:11.2.2
    container_name: dm_mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dm_network

  phpmyadmin:
    image: phpmyadmin
    container_name: dm_phpmyadmin
    restart: always
    ports:
      - '${APP_PHPMYADMIN_PORT}:80'
    environment:
      - PMA_HOST=db
    depends_on:
      - db_server
    networks:
      - dm_network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: dm_php
    ports:
      - '${APP_PORT}:80'
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db_server:3306/${MYSQL_DATABASE}?serverVersion=11.2'
    volumes:
      - ./app:/var/www/app
      - ./docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      - db_server
    networks:
      - dm_network

volumes:
  db_data:

networks:
  dm_network:
